import { v4 as uuid } from "uuid"
import type { AppState, RoadmapMonth, Skill } from "./types"

const roadmapSeed: Array<Omit<RoadmapMonth, "id">> = [
  {
    month: "2026-09",
    label: "September 2026",
    theme: "Knowledge Graph Fundamentals",
    coreSkills: ["Graphs", "RDF", "SPARQL", "Neo4j"],
    mainProject: "Urban Spatial Knowledge Graph",
    mainArticle: "Why Knowledge Graphs Could Become the Semantic Layer of Spatial Intelligence",
    openSourceObjective: "Explore Neo4j / OGC / GeoSPARQL ecosystem and make first meaningful contribution.",
    networkingObjective: "Connect with 5 people working on Knowledge Graphs and GeoAI.",
    startupObjective: "Observe spatial data workflows that feel manual or broken.",
    status: "active",
    completion: 18,
  },
  {
    month: "2026-10",
    label: "October 2026",
    theme: "Spatial Knowledge Graphs",
    coreSkills: ["GeoSPARQL", "Ontologies", "PostGIS"],
    mainProject: "Spatial reasoning layer over the Urban Knowledge Graph",
    mainArticle: "Modeling Spatial Relationships in Knowledge Graphs",
    openSourceObjective: "Contribute a fix or example to a GeoSPARQL-related repository.",
    networkingObjective: "Reconnect with 3 people from September's outreach.",
    startupObjective: "Interview one person about a spatial data pain point.",
    status: "planned",
    completion: 0,
  },
  {
    month: "2026-11",
    label: "November 2026",
    theme: "Spatial Data Engineering",
    coreSkills: ["Data Pipelines", "PostGIS", "APIs"],
    mainProject: "Spatial ETL pipeline for open geospatial datasets",
    mainArticle: "Designing Data Pipelines for Spatial Knowledge Systems",
    openSourceObjective: "Contribute to a GDAL/PROJ adjacent tool.",
    networkingObjective: "Attend one geospatial data engineering community event.",
    startupObjective: "Document 2 more observed workflow problems.",
    status: "planned",
    completion: 0,
  },
  {
    month: "2026-12",
    label: "December 2026",
    theme: "GraphRAG",
    coreSkills: ["GraphRAG", "Retrieval", "LLM Systems"],
    mainProject: "GraphRAG over the Spatial Knowledge Graph",
    mainArticle: "GraphRAG for Spatial Question Answering",
    openSourceObjective: "Publish a small GraphRAG utility as open source.",
    networkingObjective: "Share GraphRAG project with 5 relevant people.",
    startupObjective: "Assess feasibility of a GraphRAG-based product angle.",
    status: "planned",
    completion: 0,
  },
  {
    month: "2027-01",
    label: "January 2027",
    theme: "Computer Vision for Spatial Intelligence",
    coreSkills: ["Image Understanding", "Spatial ML"],
    mainProject: "Scene classification prototype on spatial imagery",
    mainArticle: "Where Computer Vision Meets Spatial Intelligence",
    openSourceObjective: "Contribute to an open CV/remote-sensing project.",
    networkingObjective: "Connect with 5 computer vision practitioners in GeoAI.",
    startupObjective: "Map CV-related problems onto the Problem Radar.",
    status: "planned",
    completion: 0,
  },
  {
    month: "2027-02",
    label: "February 2027",
    theme: "3D Reconstruction",
    coreSkills: ["Photogrammetry", "SfM", "MVS"],
    mainProject: "3D reconstruction pipeline from image sets",
    mainArticle: "A Practical Introduction to 3D Reconstruction",
    openSourceObjective: "Contribute to an SfM/MVS open-source tool.",
    networkingObjective: "Connect with 3D reconstruction researchers.",
    startupObjective: "Evaluate reconstruction-based product opportunities.",
    status: "planned",
    completion: 0,
  },
  {
    month: "2027-03",
    label: "March 2027",
    theme: "3D Scene Understanding",
    coreSkills: ["Point Clouds", "Scene Understanding"],
    mainProject: "Point cloud scene segmentation prototype",
    mainArticle: "From Point Clouds to Scene Understanding",
    openSourceObjective: "Contribute to a point-cloud processing library.",
    networkingObjective: "Present work at a local or virtual meetup.",
    startupObjective: "Validate one scene-understanding use case with a real user.",
    status: "planned",
    completion: 0,
  },
  {
    month: "2027-04",
    label: "April 2027",
    theme: "3D Spatial Knowledge Graphs",
    coreSkills: ["3D + Graphs", "Digital Twins"],
    mainProject: "Merge 3D scene data into the Spatial Knowledge Graph",
    mainArticle: "Toward 3D Spatial Knowledge Graphs",
    openSourceObjective: "Publish integration utility as open source.",
    networkingObjective: "Connect with digital twin practitioners.",
    startupObjective: "Draft an MVP concept combining 3D + graph + AI.",
    status: "planned",
    completion: 0,
  },
  {
    month: "2027-05",
    label: "May 2027",
    theme: "Temporal Spatial Intelligence",
    coreSkills: ["Spatial-Temporal Modeling"],
    mainProject: "Add temporal reasoning to the knowledge graph",
    mainArticle: "Spatial Intelligence Needs a Sense of Time",
    openSourceObjective: "Contribute temporal query examples to an ecosystem project.",
    networkingObjective: "Connect with spatial-temporal researchers.",
    startupObjective: "Test MVP concept with 2-3 target users.",
    status: "planned",
    completion: 0,
  },
  {
    month: "2027-06",
    label: "June 2027",
    theme: "Spatial Agents",
    coreSkills: ["Agents", "Tool Use"],
    mainProject: "Agent that reasons over the spatial knowledge graph",
    mainArticle: "Building Agents That Understand Space",
    openSourceObjective: "Publish an agent tool/plugin.",
    networkingObjective: "Demo the agent to the network.",
    startupObjective: "Refine MVP based on user feedback.",
    status: "planned",
    completion: 0,
  },
  {
    month: "2027-07",
    label: "July 2027",
    theme: "Spatial World Models",
    coreSkills: ["World Models"],
    mainProject: "Prototype a minimal spatial world model",
    mainArticle: "Spatial World Models: A Practical Starting Point",
    openSourceObjective: "Open source a world-model experiment.",
    networkingObjective: "Share findings with world-model research community.",
    startupObjective: "Assess technical feasibility of MVP at scale.",
    status: "planned",
    completion: 0,
  },
  {
    month: "2027-08",
    label: "August 2027",
    theme: "Productization / Startup Validation",
    coreSkills: ["Validation", "Positioning"],
    mainProject: "Package the year's work into a coherent portfolio + MVP",
    mainArticle: "What a Year of Building in Spatial Intelligence Taught Me",
    openSourceObjective: "Consolidate and polish open-source contributions.",
    networkingObjective: "Reach out to potential co-founders / early customers.",
    startupObjective: "Decide: continue validating, start building the company, or return to deep specialization.",
    status: "planned",
    completion: 0,
  },
]

const skillSeed: Array<Omit<Skill, "id">> = [
  { name: "GIS", category: "Spatial Foundations", currentLevel: 2, targetLevel: 4, importance: 4, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "Review core GIS concepts." },
  { name: "Spatial Databases", category: "Spatial Foundations", currentLevel: 2, targetLevel: 4, importance: 5, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "Set up PostGIS locally." },
  { name: "Coordinate Systems", category: "Spatial Foundations", currentLevel: 2, targetLevel: 3, importance: 3, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "Spatial Analysis", category: "Spatial Foundations", currentLevel: 1, targetLevel: 4, importance: 4, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "OGC Standards", category: "Spatial Foundations", currentLevel: 1, targetLevel: 3, importance: 3, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "GeoAI", category: "Spatial AI", currentLevel: 1, targetLevel: 4, importance: 5, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "Remote Sensing", category: "Spatial AI", currentLevel: 1, targetLevel: 3, importance: 3, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "Spatial ML", category: "Spatial AI", currentLevel: 1, targetLevel: 4, importance: 4, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "Image Understanding", category: "Spatial AI", currentLevel: 1, targetLevel: 3, importance: 3, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "Photogrammetry", category: "3D Intelligence", currentLevel: 0, targetLevel: 3, importance: 3, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "SfM", category: "3D Intelligence", currentLevel: 0, targetLevel: 3, importance: 3, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "MVS", category: "3D Intelligence", currentLevel: 0, targetLevel: 3, importance: 2, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "Point Clouds", category: "3D Intelligence", currentLevel: 0, targetLevel: 4, importance: 4, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "SLAM", category: "3D Intelligence", currentLevel: 0, targetLevel: 2, importance: 2, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "3D Reconstruction", category: "3D Intelligence", currentLevel: 0, targetLevel: 4, importance: 4, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "Scene Understanding", category: "3D Intelligence", currentLevel: 0, targetLevel: 4, importance: 4, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "Gaussian Splatting", category: "3D Intelligence", currentLevel: 0, targetLevel: 2, importance: 2, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "NeRF", category: "3D Intelligence", currentLevel: 0, targetLevel: 2, importance: 2, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "Graphs", category: "Knowledge Representation", currentLevel: 2, targetLevel: 5, importance: 5, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "Model first spatial entity relationships in Neo4j." },
  { name: "RDF", category: "Knowledge Representation", currentLevel: 1, targetLevel: 4, importance: 4, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "OWL", category: "Knowledge Representation", currentLevel: 0, targetLevel: 3, importance: 2, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "SPARQL", category: "Knowledge Representation", currentLevel: 1, targetLevel: 4, importance: 4, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "GeoSPARQL", category: "Knowledge Representation", currentLevel: 0, targetLevel: 4, importance: 5, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "Read the GeoSPARQL 1.1 spec." },
  { name: "Ontologies", category: "Knowledge Representation", currentLevel: 1, targetLevel: 3, importance: 3, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "Semantic Interoperability", category: "Knowledge Representation", currentLevel: 1, targetLevel: 3, importance: 2, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "Reasoning", category: "Knowledge Representation", currentLevel: 1, targetLevel: 3, importance: 3, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "GraphRAG", category: "AI Systems", currentLevel: 1, targetLevel: 4, importance: 4, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "Agents", category: "AI Systems", currentLevel: 2, targetLevel: 4, importance: 3, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "Tool Use", category: "AI Systems", currentLevel: 2, targetLevel: 4, importance: 3, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "Retrieval", category: "AI Systems", currentLevel: 1, targetLevel: 4, importance: 3, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "LLM Systems", category: "AI Systems", currentLevel: 2, targetLevel: 4, importance: 3, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "World Models", category: "AI Systems", currentLevel: 0, targetLevel: 2, importance: 2, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "Python", category: "Engineering", currentLevel: 4, targetLevel: 5, importance: 5, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "SQL", category: "Engineering", currentLevel: 3, targetLevel: 4, importance: 4, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "PostGIS", category: "Engineering", currentLevel: 1, targetLevel: 4, importance: 4, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "APIs", category: "Engineering", currentLevel: 3, targetLevel: 4, importance: 3, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "Docker", category: "Engineering", currentLevel: 3, targetLevel: 4, importance: 3, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "Cloud", category: "Engineering", currentLevel: 2, targetLevel: 4, importance: 3, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "Data Pipelines", category: "Engineering", currentLevel: 2, targetLevel: 4, importance: 4, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
  { name: "Testing", category: "Engineering", currentLevel: 2, targetLevel: 4, importance: 3, evidence: "", relatedProjectIds: [], lastPracticed: "", nextAction: "" },
]

export function buildSeedState(): AppState {
  const now = new Date().toISOString()
  const roadmap: RoadmapMonth[] = roadmapSeed.map((m) => ({ id: uuid(), ...m }))
  const skills: Skill[] = skillSeed.map((s) => ({ id: uuid(), ...s }))
  const currentMonth = roadmap[0]

  const seedProjectId = uuid()
  const seedArticleId = uuid()

  return {
    northStar: {
      mission:
        "Become a globally visible Spatial Intelligence Engineer and eventually build a Spatial Intelligence company.",
      specialization: "3D Spatial Understanding · Knowledge Graphs · Spatial Reasoning",
      tagline: "Building systems that help machines understand the physical world.",
    },
    currentFocus: {
      monthLabel: currentMonth.label,
      theme: currentMonth.theme,
      objective:
        "Build my first meaningful spatial knowledge graph and understand how graphs can become the semantic layer of Spatial Intelligence.",
      currentProjectId: seedProjectId,
      currentArticleId: seedArticleId,
      progress: { project: 15, article: 10, openSource: 0, network: 5, learning: 20 },
      supportingTasks: [
        { id: uuid(), title: "Set up local Neo4j instance", done: true },
        { id: uuid(), title: "Import OSM extract for target district", done: true },
        { id: uuid(), title: "Define spatial relationship schema", done: false },
        { id: uuid(), title: "Draft article outline", done: false },
        { id: uuid(), title: "Identify 5 people to connect with this month", done: false },
      ],
    },
    todayAction: {
      title: "Implement spatial relationships between OSM entities in Neo4j.",
      why: "This is the foundation of the Urban Spatial Knowledge Graph and unblocks the first article.",
      effort: "~2 hours",
      relatedObjective: "Build first meaningful spatial knowledge graph (September objective).",
    },
    monthlyScorecard: { project: 15, article: 10, openSource: 0, network: 5, startupDiscovery: 0 },
    roadmap,
    projects: [
      {
        id: seedProjectId,
        title: "Urban Spatial Knowledge Graph",
        problem: "Urban spatial data is fragmented across formats and lacks a coherent semantic layer.",
        motivation: "Understand how knowledge graphs can become the semantic layer of Spatial Intelligence.",
        technicalTopic: "Knowledge Graphs + Spatial Reasoning",
        technologies: ["Neo4j", "OSM", "GeoSPARQL", "Python"],
        dataset: "OpenStreetMap extract of a city district",
        architecture: "OSM ingestion → spatial entity extraction → Neo4j graph → spatial relation queries",
        status: "BUILDING",
        startDate: currentMonth.month + "-01",
        targetDate: "2026-09-30",
        githubUrl: "",
        demoUrl: "",
        articleUrl: "",
        notes: "",
        results: "",
        failureCases: "",
        lessonsLearned: "",
        futureWork: "",
        roadmapMonthId: currentMonth.id,
        createdAt: now,
        updatedAt: now,
      },
    ],
    articles: [
      {
        id: seedArticleId,
        title: "Why Knowledge Graphs Could Become the Semantic Layer of Spatial Intelligence",
        status: "DRAFT",
        topic: "Knowledge Graphs, Spatial Intelligence",
        targetAudience: "Spatial AI / GeoAI engineers and researchers",
        outline: "",
        draftLink: "",
        publicationLink: "",
        publicationDate: "",
        relatedProjectId: seedProjectId,
        createdAt: now,
        updatedAt: now,
      },
    ],
    openSource: [],
    people: [],
    problems: [],
    skills,
    weeklyReviews: [],
    monthlyReviews: [],
    quarterlyReviews: [],
    notes: [],
    decisions: [],
    dailyEntries: [],
    globalPositioning: [
      { id: uuid(), category: "role", name: "Spatial Intelligence Engineer", notes: "", status: "target" },
      { id: uuid(), category: "role", name: "Geospatial AI Engineer", notes: "", status: "target" },
      { id: uuid(), category: "role", name: "3D Computer Vision Engineer", notes: "", status: "target" },
      { id: uuid(), category: "role", name: "Knowledge Graph Engineer", notes: "", status: "target" },
    ],
    founderMode: [],
    settings: { onboardingComplete: false, clarityModeTodayActionId: null },
  }
}
